export const members = [
  {
    id: "401361",
    nickname: "ปู้ปู่",
    fullname: "สรทรัพย์ ลีลาตังวัฒน์",
    quote: `“เพราะรักทำร้าย เลยย้ายมาทำรถ”`,
    cv: "https://drive.google.com/file/d/1T8xaPOZTwC3ORXw1vAGkGvvRm5m-eLu1/view?usp=sharing",
    github: "https://github.com/ZorraZabb",
    linkedin:
      "https://www.linkedin.com/in/sorrasub-leelatangwat?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app",
  },
  {
    id: "401173",
    nickname: "เคนตะ",
    fullname: "วงศ์ไกรวิชชญ์ ชื่นชมภู",
    quote: `Super "DevOps" Engineer`,
    cv: "https://drive.google.com/file/d/1Q-cn1ujpBeDlWF1pK1ONpp5wPvjHqyKS/view?usp=drive_link",
    github: "https://github.com/kentakoong",
    linkedin:
      "https://www.linkedin.com/in/wongkraiwich-chuenchomphu-80212a201/",
  },
  {
    id: "400646",
    nickname: "แจ๊ค",
    fullname: "เจษฎา ปราณี",
    quote: ``,
    cv: "https://drive.google.com/file/d/1UFwczjj8Ro9Ne5Lz_fVUZgvf9rdqmkr0/view",
    github: "https://github.com/JackJessada",
  },
  {
    id: "404790",
    nickname: "ฟาโรห์",
    fullname: "อรรถพล ทองวิชิต",
    quote: `"เหนื่อยก็พัก เจอ BUG ก็อย่าท้อ"`,
    cv: "https://drive.google.com/file/d/1b0IstCp6fo68V_NN_MRzmN_G4SFCBAi6/view",
    github: "https://github.com/falotoyo18",
    linkedin: "https://www.linkedin.com/in/auttaphol-thongvichit-78192b110/",
  },
  {
    id: "400735",
    nickname: "อาร์เธอร์",
    fullname: "วาธิน พรมฝ้าย",
    quote: `CUDA out of memory`,
    cv: "https://drive.google.com/file/d/1oB7CMBA6z9-8XISmNUsfG46g4lYixmkF/view?usp=drive_link",
    github: "https://github.com/E27-25",
  },
  {
    id: "402167",
    nickname: "โก้",
    fullname: "เจษฎา ฤกษ์ลัดดาพรรณ",
    quote: `"WORK HARD PLAY HARDER"`,
  },
  {
    id: "401722",
    nickname: "โบ้ต",
    fullname: "ปิยะวัฒน์ ตั้งพงษ์",
    quote: `"Ai จะเก่งอยู่ที่ data"`,
    cv: "https://drive.google.com/file/d/1EmCxPymZ88sz4_rSlLiw7nKF4TFmSz7q/view?usp=sharing",
    github: "https://github.com/piyaboat",
  },
  {
    id: "402871",
    nickname: "เดียร์",
    fullname: "นรากรณ์ ดีเย็น",
    quote: `"งานหนักไม่ว่า แต่ขอนอนก่อน"`,
    cv: "https://drive.google.com/file/d/1JsQxpFpbIKX3TD2iPFezQd5Eiyk41qgH/view",
    github: "https://github.com/Dearnarakorn",
    linkedin: "https://www.linkedin.com/in/narakorn-deeyen/",
  },
  {
    id: "401102",
    nickname: "ปิง",
    fullname: "นพกร สุรินทร์",
    quote: `ไม่ต้องถามหา ถึงเวลาเดี๋ยวมาให้เห็น`,
    cv: "https://www.canva.com/design/DAF_lbBP3Vc/Bt_FBj0LnGdvTY2X32ORPA/view?utm_content=DAF_lbBP3Vc&utm_campaign=designshare&utm_medium=link&utm_source=editor",
  },
  {
    id: "403888",
    nickname: "พีค",
    fullname: "ปัณณทัต ปัณฑรานุวงศ์",
    quote: `"ฤกษ์ที่ดี คือ เลิกงานกลับบ้านได้"`,

    github: "https://github.com/peak-pan",
    linkedin: "www.linkedin.com/in/pannathad-panthanuwong-b0557a279",
  },
  {
    id: "400280",
    nickname: "ตัง",
    fullname: "ทินภัทร ดีเดช",
    quote: `ฮาดีมีรางวัล`,
    cv: "https://drive.google.com/file/d/1CYJNy8cgjSv0hAXduRFUw2VcwIwDkgPQ/view?usp=sharing",
    github: "https://github.com/SThinnaphat",
    linkedin: "https://www.linkedin.com/in/thinnaphat-deedetch-203380220/",
  },
  {
    id: "401675",
    nickname: "มิก",
    fullname: "สุเมธ คุ้มคง",
    quote: `"ถ้าเวลาคือคำตอบ ทำไมตอนสอบไม่ลอกนาฬิกา"`,
  },
  {
    id: "402271",
    nickname: "ฟาอิฟ",
    fullname: "ฟาอิฟ เจ๊ะมาด",
    quote: `ชีวิตเป็นโสด ขอโค้ดเพื่อนอีก`,

    github: "https://github.com/znet2",
  },
  {
    id: "404424",
    nickname: "ชาญ",
    fullname: "ชาญธิษณ์ พัวศิริ",
    quote: `"never surrender"`,
    cv: "https://drive.google.com/file/d/1R1Fz6igTamYNfHUFoqY_4JlMEY3QmCfe/view?usp=sharing",
    github: "https://github.com/channo39mz",
  },
  {
    id: "401782",
    nickname: "บัว",
    fullname: "ปุญชรัสมิ์ สุตันตยาวลี",
    quote: `"เข้าทุกคาบ ไม่ทราบอะไรเลย"`,
    cv: "https://drive.google.com/file/d/1W-SZYWWqL2XSuqjMvL3f0PdfGv0tJ9nU/view?usp=sharing",
  },
  {
    id: "402728",
    nickname: "เก๋า",
    fullname: "บุริศร์ บริบูรณ์",
    quote: `ผมเก๋าครับ`,
    cv: "https://drive.google.com/file/d/1FpIFGkwQuQ6k5dxwuHmoQM24uTChTYHH/view",
    github: "https://github.com/K-Burit",
  },
  {
    id: "400307",
    nickname: "โอม",
    fullname: "ก้องภพ กองเกียรติเจริญ",
    quote: `"หล่อเท่ เก๋สมาร์ทสมอง เนียบ เฉียบ ปิ๊ง"`,
    cv: "https://drive.google.com/file/d/16LXtC0zeExtBm8A7Ol-XS7iFJSY7i90s/view?usp=sharing",
    github: "https://github.com/Yuurisuu",
  },
  {
    id: "403308",
    nickname: "ปั๊บ",
    fullname: "อภิวิชษ์ สายภู่",
    quote: `"นอนน้อย แต่นอนนะ"`,

    github: "https://github.com/ggpupkill",
  },
  {
    id: "400158",
    nickname: "ภีม",
    fullname: "สิรวุฒิ ชูหนู",
    quote: `"คนคอนยิงใครยิงจริง"`,
    cv: "https://1drv.ms/b/s!AqQjnWx2g-dIlH_4ljDY1xw9lJol",
    github: "https://github.com/wirepecion",
  },
  {
    id: "404379",
    nickname: "หวาย",
    fullname: "สหชา อินทร์ไชย",
    quote: `Don't talk to me, I'm a Developer`,
    cv: "https://drive.google.com/file/d/11_JfcxOjOw3cbsz0vEOqLkSAyPge9NWY/view?usp=sharing",
    github: "https://github.com/S0l0Mont",
  },
  {
    id: "403001",
    nickname: "ปังปอนด์",
    fullname: "ปณชัย ลิขิตปัญญาราษฎร์",
    quote: ``,
    cv: "https://drive.google.com/file/d/1BUdi8eYNmzr_R3-oOnuq1B6yyFul1Wyd/view?usp=sharing",
    github: "https://github.com/417-Panachai",
    linkedin: "https://www.linkedin.com/in/panachai-likhitpanyarat/",
  },
  {
    id: "400275",
    nickname: "ไว",
    fullname: "นพณัฐ ประเสริฐวงษา",
    quote: `มาแน่ถ้าแม่ไม่ว่า`,
  },
  {
    id: "401200",
    nickname: "เจเจ",
    fullname: "จุฬารัตน์ อภิวงค์",
    quote: `ชีวิตไม่แน่นอน แต่วันนี้ต้องได้นอน`,
    cv: "https://drive.google.com/file/d/1-tlGqHvLXvZbAbIZqpSypfXBNgKyD1P-/view?usp=sharing",
  },
  {
    id: "400353",
    nickname: "น้ำผึ้ง",
    fullname: "รมิตา ศรีภูธร",
    quote: `รองเท้าไม่ซิ่งอย่ามาวิ่งกับหนู`,
    cv: "https://drive.google.com/file/d/15aj0ms5PiES_UEFwtaWeWTFZkzeB-Kn2/view",
    github: "https://github.com/MinakoNG63",
  },
  {
    id: "402500",
    nickname: "ไนน์",
    fullname: "เนติชัย วงษ์คำภู",
    quote: `“ข้าวซอยลำๆ”`,

    github: "https://github.com/EventHorizon04",
    linkedin: "https://th.linkedin.com/in/netichai-wongkhamphu-275601246",
  },
  {
    id: "402090",
    nickname: "กิ๊ก",
    fullname: "เนตรนภา สิทธิหาโคตร",
    quote: `เดิมๆ`,
    cv: "https://www.linkedin.com/posts/netnapa-sittihakote-b925a9278_resumenetnapa-activity-7174356799507091457-PfcJ/?utm_source=share&utm_medium=member_desktop",
  },
  {
    id: "402317",
    nickname: "หนุ่ม",
    fullname: "สิทธิโชค โสมอ่ำ",
    quote: `the best model is human force algorithm`,
    cv: "https://drive.google.com/drive/folders/1ctfiNplKmWydq46NrU-6ozoZbX0Kj9L3",
    github: "https://github.com/numbernard",
  },
];
